___

#5 TOPIC MODELLING
___

# Latent Dirichlet Allocation

## Data

We will be using articles from NPR (National Public Radio), obtained from their website [www.npr.org](http://www.npr.org)

In [7]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/nluninja/text-mining-dataviz/refs/heads/main/4.%20Topic%20Modeling/npr.csv'

In [8]:
npr = pd.read_csv(url)

In [9]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

Notice how we don't have the topic of the articles! Let's use LDA to attempt to figure out clusters of the articles.

In [10]:
npr.shape

(11992, 1)

## Preprocessing

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [12]:
cv = CountVectorizer(max_df=0.95, min_df=0.2, stop_words='english')

In [13]:
dtm = cv.fit_transform(npr['Article'])

In [14]:
dtm

<11992x96 sparse matrix of type '<class 'numpy.int64'>'
	with 349867 stored elements in Compressed Sparse Row format>

## LDA

In [15]:
from sklearn.decomposition import LatentDirichletAllocation

In [16]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [17]:
# This can take awhile, we're dealing with a large amount of documents!
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

## Showing Stored Words

In [18]:
len(cv.get_feature_names_out())

96

### Showing Top Words Per Topic

In [19]:
len(LDA.components_)

7

In [20]:
LDA.components_

array([[2.43552043e+02, 1.34337302e+02, 3.85012991e+02, 7.85466726e+01,
        8.58021410e+01, 3.71066582e+01, 1.02165432e+02, 1.49881745e+02,
        2.48899977e+02, 7.24307362e+01, 3.91892846e+01, 3.81252943e+02,
        5.98765972e+02, 1.85213664e+02, 1.97551725e+02, 3.15542050e+02,
        1.34984408e+02, 8.09879612e+01, 1.73488352e+02, 6.84674431e+01,
        1.20871402e+02, 2.77045500e+02, 3.00286106e+02, 1.08809507e+02,
        3.70254714e+02, 1.43418045e+02, 1.70030265e+02, 6.59535121e+01,
        2.55749281e+02, 4.40564435e+02, 1.50835273e+02, 5.69013850e+01,
        3.68657784e+02, 1.55580193e+02, 3.10236425e+02, 3.11392135e+02,
        1.36019955e+02, 2.10801949e+02, 5.42806305e+02, 5.11214933e+01,
        1.43558915e+02, 3.88475625e+01, 8.25815860e+00, 4.16206831e+02,
        1.28422940e+02, 8.99068319e+01, 1.70036766e+02, 1.35189212e+02,
        1.64264561e+02, 5.55664288e+02, 2.17691616e+02, 5.46762754e+02,
        4.40447399e+02, 1.54030540e+03, 4.65260751e+01, 2.133737

In [21]:
len(LDA.components_[0])

96

In [22]:
single_topic = LDA.components_[0]

In [23]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([80, 90, 93, 42, 79, 78, 71, 76, 89, 72,  5, 41, 10, 54, 39, 31, 27,
       19,  9,  3, 17, 60,  4, 45, 63, 92,  6, 67, 23, 81, 91, 77, 20, 73,
       44,  1, 16, 47, 36, 56, 25, 40,  7, 30, 59, 33, 48, 85, 61, 26, 46,
       18, 86, 13, 74, 84, 14, 37, 55, 50,  0,  8, 28, 82, 21, 87, 22, 65,
       75, 64, 34, 35, 15, 88, 95, 32, 24, 11,  2, 58, 43, 66, 52, 29, 83,
       38, 51, 49, 12, 57, 94, 68, 62, 53, 70, 69], dtype=int64)

In [24]:
# Word least representative of this topic
single_topic[80]

0.14316194780333685

In [25]:
# Word most representative of this topic
single_topic[69]

9335.872540018545

In [26]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([51, 49, 12, 57, 94, 68, 62, 53, 70, 69], dtype=int64)

In [27]:
top_word_indices = single_topic.argsort()[-10:]

In [28]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

national
make
change
people
year
says
public
new
states
state


These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [29]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['say', 'need', 'going', 'use', 'just', 'national', 'make', 'change', 'people', 'year', 'says', 'public', 'new', 'states', 'state']


THE TOP 15 WORDS FOR TOPIC #1
['10', 'president', 'government', 'national', 'according', 'white', 'new', 'world', '000', 'american', 'years', 'country', 'year', 'people', 'percent']


THE TOP 15 WORDS FOR TOPIC #2
['lot', 'time', 'things', 'make', 've', 'going', 'new', 'don', 'really', 'way', 'know', 'just', 'think', 'people', 'like']


THE TOP 15 WORDS FOR TOPIC #3
['called', 'national', 'including', 'say', 'time', 'public', 'case', 'according', 'new', 'government', 'news', 'told', 'npr', 'people', 'said']


THE TOP 15 WORDS FOR TOPIC #4
['year', 'use', 'say', 'make', 'help', 'time', 'work', 'don', 'university', 'years', 'new', 'just', 'like', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #5
['went', 'story', 'got', 'know', 'did', 'home', 'said', 'didn', 'day', 'years', 'like', 'family', 'life', 'time', 'just']


THE TOP 1

### Attaching Discovered Topic Labels to Original Articles

In [30]:
dtm

<11992x96 sparse matrix of type '<class 'numpy.int64'>'
	with 349867 stored elements in Compressed Sparse Row format>

In [31]:
dtm.shape

(11992, 96)

In [32]:
len(npr)

11992

In [33]:
topic_results = LDA.transform(dtm)

In [34]:
topic_results.shape

(11992, 7)

In [35]:
topic_results[0]

array([0.00150811, 0.15559485, 0.11719971, 0.0015108 , 0.00150898,
       0.00151116, 0.72116638])

In [36]:
topic_results[0].round(2)

array([0.  , 0.16, 0.12, 0.  , 0.  , 0.  , 0.72])

In [37]:
topic_results[0].argmax()

6

This means that our model thinks that the first article belongs to topic #7.

### Combining with Original Data

In [38]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [39]:
topic_results.argmax(axis=1)

array([6, 6, 6, ..., 5, 2, 4], dtype=int64)

In [40]:
npr['Topic'] = topic_results.argmax(axis=1)

In [41]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      6
1    Donald Trump has used Twitter  —   his prefe...      6
2    Donald Trump is unabashedly praising Russian...      6
3  Updated at 2:50 p. m. ET, Russian President Vl...      6
4  From photography, illustration and video, to d...      1
5  I did not want to join yoga class. I hated tho...      2
6  With a   who has publicly supported the debunk...      4
7  I was standing by the airport exit, debating w...      5
8  If movies were trying to be more realistic, pe...      4
9  Eighteen years ago, on New Year’s Eve, David F...      2

## Visualizing LDA

**pyLDAvis** is designed to help users interpret the topics in a topic model that has been fit to a corpus of text data. The package extracts information from a fitted LDA topic model to inform an interactive web-based visualization.

it's a Python library for interactive topic model visualization, port of the fabulous R package by Carson Sievert and Kenny Shirley.

In [42]:
!pip install pyldavis


[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


pyLDAvis now also supports LDA application from scikit-learn, but also gensim, that is an alternative library for LDA

In [43]:
import pyLDAvis
import pyLDAvis.lda_model
pyLDAvis.enable_notebook()

In [44]:
pyLDAvis.lda_model.prepare(LDA, dtm, cv)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
2     -0.123896 -0.064762       1        1  24.331129
4     -0.119128  0.029904       2        1  20.704365
5     -0.074972 -0.123621       3        1  13.958827
3      0.107343  0.012570       4        1  13.585422
6      0.184660 -0.091761       5        1  12.123409
1      0.026972  0.075075       6        1  10.287665
0     -0.000979  0.162596       7        1   5.009182, topic_info=       Term          Freq         Total Category  logprob  loglift
80    trump  22693.000000  22693.000000  Default  30.0000  30.0000
68     says  45265.000000  45265.000000  Default  29.0000  29.0000
69    state  10172.000000  10172.000000  Default  28.0000  28.0000
65     said  28716.000000  28716.000000  Default  27.0000  27.0000
58  percent   8137.000000   8137.000000  Default  26.0000  26.0000
..      ...           ...           ...      ...      ...      ...
43     like    420.388969  21480.621703   Topic7  -4.4337  -0.9398
95    years    349.961968  13111.428008   Topic7  -4.6171  -0.6295
87      way    298.786676  10298.184180   Topic7  -4.7752  -0.5461
75     time    303.709706  14516.968436   Topic7  -4.7589  -0.8731
65     said    303.560085  28716.513240   Topic7  -4.7593  -1.5558

[298 rows x 6 columns], token_table=      Topic      Freq   Term
term                        
0         1  0.009308    000
0         2  0.255526    000
0         3  0.008031    000
0         4  0.209349    000
0         5  0.002555    000
...     ...       ...    ...
95        3  0.241011  years
95        4  0.112879  years
95        5  0.024101  years
95        6  0.222935  years
95        7  0.026694  years

[667 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[3, 5, 6, 4, 7, 2, 1])

pyLDAvis reference paper: https://cran.r-project.org/web/packages/LDAvis/vignettes/details.pdf
relevance definition: https://nlp.stanford.edu/events/illvi2014/papers/sievert-illvi2014.pdf